In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('../../US_Accidents_May19_Migrated Data.csv')

In [12]:
df.head()

,Airport_Code,Amenity,Astronomical_Twilight,Bump,Calculation1,City,Civil_Twilight,count of Bump,Count of Crossing,count Traffic Signal,...,Humidity(%),Number of Records,Precipitation(in),Pressure(in),Records,Start_Lat,Start_Lng,TMC,Wind_Chill(F),Wind_Speed(mph)
0,NaN,False,Day,False,Remaining,Garnet Valley,Day,0,0,0,...,NaN,1,NaN,NaN,1,39.852940,-75.461739,201.0,NaN,NaN
1,KDWH,False,Day,False,Remaining,Spring,Day,0,0,0,...,82.0,1,NaN,30.02,1,30.159246,-95.510826,201.0,NaN,5.8
2,KDSM,False,Day,False,Remaining,West des Moines,Day,0,0,0,...,79.0,1,NaN,30.04,1,41.586887,-93.806496,201.0,34.3,11.5
3,KCPS,False,Day,False,Remaining,Saint Louis,Day,0,0,0,...,84.0,1,NaN,30.10,1,38.634579,-90.186806,201.0,NaN,12.7
4,KXBP,False,Day,False,Remaining,Springtown,Day,0,0,0,...,96.0,1,NaN,29.95,1,32.930958,-97.641068,201.0,NaN,5.8

In [13]:
df.shape

(2243939, 57)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2243939 entries, 0 to 2243938
Data columns (total 57 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Airport_Code           object
 1   Amenity                bool
 2   Astronomical_Twilight  object
 3   Bump                   bool
 4   Calculation1           object
 5   City                   object
 6   Civil_Twilight         object
 7   count of Bump          int64
 8   Count of Crossing      int64
 9   count Traffic Signal   int64
 10  Country                object
 11  County                 object
 12  Crossing               bool
 13  Description            object
 14  End_Lat                float64
 15  End_Lng                float64
 16  End_Time               object
 17  Give_Way               bool
 18  ID                     object
 19  Junction               bool
 20  Nautical_Twilight      object
 21  No_Exit                bool
 22  Number                 float64
 23  Railway                bool
 24  Roundabout             bool
 25  Severity               int64
 26  Side                   object
 27  Source                 object
 28  Start_Time             object
 29  State                  object
 30  Station                bool
 31  Stop                   bool
 32  Street                 object
 33  Sunrise_Sunset         object
 34  Temperature(F)         float64
 35  Timezone               object
 36  Traffic_Calming        bool
 37  Traffic_Signal         bool
 38  Turning_Loop           bool
 39  Visibility(mi)         float64
 40  Weather_Condition      object
 41  Weather_Timestamp      object
 42  Wind_Direction         object
 43  Zipcode                object
 44  Count of accidents     int64
 45  count of county        int64
 46  Distance(mi)           float64
 47  Humidity(%)            float64
 48  Number of Records      int64
 49  Precipitation(in)      float64
 50  Pressure(in)           float64
 51  Records                int64
 52  Start_Lat              float64
 53  Start_Lng              float64
 54  TMC                    float64
 55  Wind_Chill(F)          float64
 56  Wind_Speed(mph)        float64
dtypes: bool(13), float64(14), int64(8), object(22)
memory usage: 781.1+ MB

In [15]:
df.describe()

,count of Bump,Count of Crossing,count Traffic Signal,End_Lat,End_Lng,Number,Severity,Temperature(F),Visibility(mi),Count of accidents,...,Humidity(%),Number of Records,Precipitation(in),Pressure(in),Records,Start_Lat,Start_Lng,TMC,Wind_Chill(F),Wind_Speed(mph)
count,2.243939e+06,2.243939e+06,2.243939e+06,516762.000000,516762.000000,785537.000000,2.243939e+06,2.181674e+06,2.172579e+06,2.243939e+06,...,2.179472e+06,2243939.0,264473.000000,2.186659e+06,2.243939e+06,2.243939e+06,2.243939e+06,1.727177e+06,391569.000000,1.800985e+06
mean,1.065091e-04,5.427197e-02,1.598297e-01,37.443109,-96.527543,5625.281008,2.382692e+00,6.123244e+01,9.124096e+00,9.997121e-01,...,6.592758e+01,1.0,0.060439,3.003747e+01,9.997121e-01,3.646348e+01,-9.485567e+01,2.073527e+02,26.042067,8.844042e+00
std,1.031978e-02,2.265536e-01,3.664481e-01,5.126585,17.986406,11071.872898,5.488029e-01,1.914616e+01,2.986359e+00,1.696478e-02,...,2.243013e+01,0.0,0.439698,2.267242e-01,1.696478e-02,4.958759e+00,1.709453e+01,1.940527e+01,13.478333,4.973200e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,24.570110,-124.497829,1.000000,0.000000e+00,-7.780000e+01,0.000000e+00,0.000000e+00,...,4.000000e+00,1.0,0.000000,0.000000e+00,0.000000e+00,2.457022e+01,-1.246238e+02,2.000000e+02,-65.900000,1.200000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,33.887450,-117.870577,803.000000,2.000000e+00,4.890000e+01,1.000000e+01,1.000000e+00,...,5.000000e+01,1.0,0.000000,2.992000e+01,1.000000e+00,3.348468e+01,-1.171362e+02,2.010000e+02,19.200000,5.800000e+00
50%,0.000000e+00,0.000000e+00,0.000000e+00,38.038480,-90.192310,2672.000000,2.000000e+00,6.300000e+01,1.000000e+01,1.000000e+00,...,6.800000e+01,1.0,0.010000,3.003000e+01,1.000000e+00,3.586428e+01,-8.818469e+01,2.010000e+02,28.700000,8.100000e+00
75%,0.000000e+00,0.000000e+00,0.000000e+00,41.393320,-80.895040,6846.000000,3.000000e+00,7.590000e+01,1.000000e+01,1.000000e+00,...,8.500000e+01,1.0,0.040000,3.015000e+01,1.000000e+00,4.042111e+01,-8.085453e+01,2.010000e+02,36.400000,1.150000e+01
max,1.000000e+00,1.000000e+00,1.000000e+00,49.075000,-67.109242,961052.000000,4.000000e+00,1.706000e+02,1.400000e+02,1.000000e+00,...,1.000000e+02,1.0,10.800000,3.304000e+01,1.000000e+00,4.900076e+01,-6.711317e+01,4.060000e+02,45.200000,8.228000e+02